---
title: "不同契約人力工作性質與薪資待遇之差異"
author: "Jerry Yang，楊宗政"
output: github_document
---

```{r setup,echo=T, eval=T , warning=FALSE, message=FALSE}
knitr::opts_chunk$set(echo = TRUE)
options(htmltools.dir.version = FALSE)
sjPlot::set_theme(theme.font="PingFang TC") #解決底下有框框問題
library(ggplot2)
library(sjlabelled)
library(sjmisc)
library(sjPlot)
library(GGally)
```

# 先讀入契約人力問卷調查資料  
檔案形式為sav檔，會先用sav檔讀入，在儲存成rda檔做分析

## 讀入sav檔並儲存成rda檔  
問卷資料用contract_staff來存放
```{r sav, echo=T, eval=T , warning=FALSE}
contract_staff <- read_spss("~/Documents/2021TextbookProject/契約人力問卷調查.sav")

#將sav檔儲存成rda檔
save(contract_staff, file = "~/Documents/2021TextbookProject/契約人力問卷調查.rda",compress = T)

rm(list=ls())
```

## 讀入rda檔
檢查contract_staff的屬性
```{r rda, cache=TRUE , message=FALSE, warning=FALSE}
load("契約人力問卷調查.rda")
nrow(contract_staff)
names(contract_staff)
class(contract_staff)
```


## 將變數名稱修改,並重新命名變數
```{r 命名變數, cache=TRUE, warning=FALSE,message=FALSE}
#重新命名變數
contract_staff$G01[contract_staff$G01 == 1] <- "聘用人員"
contract_staff$G01[contract_staff$G01 == 2] <- "約僱人員"
contract_staff$G01[contract_staff$G01 == 3] <- "臨時人員"

contract_staff$W4[contract_staff$W4 == 1] <- "行政庶務"
contract_staff$W4[contract_staff$W4 == 2] <- "專業研究性"
contract_staff$W4[contract_staff$W4 == 3] <- "技術性"
contract_staff$W4[contract_staff$W4 == 4] <- "民眾服務"

contract_staff$H3[contract_staff$H3 == 1] <- "2萬-3萬"
contract_staff$H3[contract_staff$H3 == 2] <- "3萬-4萬"
contract_staff$H3[contract_staff$H3 == 3] <- "4萬-5萬"
contract_staff$H3[contract_staff$H3 == 4] <- "5萬-6萬"
contract_staff$H3[contract_staff$H3 == 5] <- "6萬以上"

contract_staff$education[contract_staff$education == 1] <- "高中高職或以下"
contract_staff$education[contract_staff$education == 2] <- "專科"
contract_staff$education[contract_staff$education == 3] <- "大學"
contract_staff$education[contract_staff$education == 4] <- "碩士以上"

contract_staff$H2[contract_staff$H2 == 1] <- "少於1年"
contract_staff$H2[contract_staff$H2 == 2] <- "1-9年"
contract_staff$H2[contract_staff$H2 == 3] <- "10-19年"
contract_staff$H2[contract_staff$H2 == 4] <- "20-29年"
contract_staff$H2[contract_staff$H2 == 5] <- "30年以上"

#查找變數在第幾列
which(colnames(contract_staff) == "G01")
which(colnames(contract_staff) == "W4")
which(colnames(contract_staff) == "F06")
which(colnames(contract_staff) == "H3")
which(colnames(contract_staff) == "education")
which(colnames(contract_staff) == "F04")
which(colnames(contract_staff) == "F05")
which(colnames(contract_staff) == "H2")


#重新命名變數名稱
names(contract_staff)[73] <- "契約人力"
names(contract_staff)[90] <- "工作性質"
names(contract_staff)[70] <- "薪資待遇"
names(contract_staff)[81] <- "月薪資區間"
names(contract_staff)[91] <- "學歷"
names(contract_staff)[68] <- "學歷程度"
names(contract_staff)[69] <- "現職機關工作年資"
names(contract_staff)[80] <- "工作年資區間"

```

```{r 工作年資與學歷, fig.cap = "工作年資與學歷的差異。", warning=FALSE, cache=TRUE, message=FALSE}
contract_staff$學歷 <- factor(contract_staff$學歷, c("高中高職或以下", "專科", "大學", "碩士以上"))#由於長條圖不會自己排序資料，因此轉換成factor格式，再根據自己定義的順序排序。
ggplot(contract_staff, aes(x = 工作年資區間, fill = 學歷)) + 
  geom_bar(position = "dodge") + facet_wrap(~契約人力)+ theme(strip.text.x = element_text(size = 12)) + labs(y = "次數", size = 10) + geom_text(stat = "count", aes(label = ( ..count..)), vjust = 1, color = I("black"), size = 4) + theme(text = element_text(family = "黑體-繁 中黑", size = 7))
```


```{r 年資與薪資待遇, fig.cap = "工作年資與學歷的描述性統計。", warning=FALSE, cache=TRUE, message=FALSE}
ggplot(contract_staff, aes(x = 現職機關工作年資, y = 薪資待遇, colour = 契約人力))+
  geom_point()+geom_smooth()
```


```{r 年齡與薪資待遇, fig.cap = "年齡與薪資待遇的差異。", warning=FALSE, cache=TRUE, message=FALSE}
ggplot(contract_staff, aes(x = 年齡, y = 薪資待遇, colour = 契約人力))+
  geom_point()+geom_smooth()
```


```{r 月薪資與工作性質, fig.cap = "月薪資與工作性質的差異。", warning=FALSE, cache=TRUE, message=FALSE}
ggplot(data = contract_staff, aes(x = 月薪資區間, y = 工作性質, 
                      color = 契約人力, shape = 契約人力)) + 
  geom_jitter(alpha = 1/2, size = 3.5) + 
  geom_smooth(method = "lm", se = FALSE)

```


```{r 相關性1, fig.cap = "薪資待遇、學歷、工作年資及年齡的相關性1。", warning=FALSE, cache=TRUE, message=FALSE}
constract.df = contract_staff[, c("薪資待遇", "學歷程度", "現職機關工作年資", "年齡")]
cor.mat = cor(constract.df, use = "complete", method = "pearson")
round(cor.mat, 4)
pairs(constract.df, main = "中文標題", family = "黑體-繁 中黑") + theme(plot.title = element_text(size = 20, color = "red", hjust = 0.5, family = "PingFang TC"), legend.position = "right")
```


```{r 相關性2, fig.cap = "薪資待遇、學歷、工作年資及年齡的相關性2。", warning=FALSE, cache=TRUE, message=FALSE}
GGally::ggpairs(data = constract.df)
GGally::ggcorr(data = constract.df, 
               method = c("complete", "pearson"))
```


```{r 相關性3, fig.cap = "薪資待遇、學歷、工作年資及年齡的相關性3。", warning=FALSE, cache=TRUE, message=FALSE}
my_fn <- function(data, mapping, ...){
  p <- ggplot(data = data, mapping = mapping) + 
    geom_point() +
    geom_smooth(method = lm, se = FALSE, fill = "blue", color = "blue", ...)
  p
}
GGally::ggpairs(data = constract.df, 
        lower = list(continuous = my_fn)) + theme(text = element_text(family = "黑體-繁 中黑", size = 10))
```


```{r 月薪資與學歷的差異, fig.cap = "月薪資與學歷在不同工作性質及契約人力下的差異。", warning=FALSE, cache=TRUE, message=FALSE}
contract_staff$學歷 <- factor(contract_staff$學歷, c("高中高職或以下", "專科", "大學", "碩士以上"))
ggplot(data = contract_staff, aes(x = 月薪資區間, y =  學歷)) + labs(x = "月薪資", y = "學歷", title = "月薪資與學歷之差異") + geom_jitter() + facet_grid(工作性質 ~ 契約人力) + theme(strip.text.x = element_text(size = 12) ) +  theme(strip.text.y = element_text(size = 10) ) + theme(plot.title = element_text(size = 10, face = "bold", color = "black"), axis.title = element_text(size = 12)) + theme(text = element_text(family = "黑體-繁 中黑", size = 9))


```



